import type { MockTest, TestStep } from "./types"
import { LISTENING_BLUEPRINT } from "./listening-blueprint"

const HEADER_BASE = "Advanced Mock Exam 5 - Listening"

function q(
  id: string,
  header: string,
  prompt: string,
  options: [string, string, string, string],
  correctIndex: number,
): TestStep {
  return {
    id,
    kind: "audio-mcq",
    headerTitle: header,
    instruction: "Listen to the question. You will hear it only once.",
    answerSeconds: 30,
    script: [{ text: prompt }],
    question: {
      id,
      prompt,
      correctOptionId: `${id}-${correctIndex}`,
      options: options.map((text, i) => ({ id: `${id}-${i}`, text })),
    },
  }
}

const steps: TestStep[] = [
  {
    id: "intro",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} - CELPIP Test`,
    sectionTitle: "Listening Test Instructions",
    bullets: [
      "This advanced Listening section uses longer clips, faster natural speech, and speakers who qualify, hedge, and revise what they say.",
      "You will hear each clip only once. The correct answer often depends on a single conditional phrase — 'unless', 'only if', 'except', 'apart from'.",
      "Expect distractors that repeat exact words from the audio but attach them to the wrong idea.",
      "There are six parts and 38 questions in total.",
    ],
  },
  {
    id: "video",
    kind: "video",
    headerTitle: `${HEADER_BASE} - Instructional Video`,
    heading: "Listening Video Instructions",
    posterSrc: "/mock-test/listening-video-poster.png",
    narration:
      "Welcome to Advanced Mock Exam 5. This Listening section will test your ability to hold several details in mind at once and to distinguish a speaker's firm conclusion from the possibilities they merely considered. Listen all the way to the end of each turn before deciding, because speakers frequently reverse an earlier statement. When you are ready, select Next to begin.",
  },
  {
    id: "practice",
    kind: "audio",
    headerTitle: `${HEADER_BASE} - Practice Task`,
    instruction: "Practice Task: Check your headphones. You will hear a short sample.",
    script: [
      { text: "This is a sound check. Listen for conditions: 'The refund is automatic, except for items bought on sale, which need a receipt.' If the item was on sale, a receipt is required. Adjust your volume, then select Next to begin." },
    ],
    transcript:
      "A sound check demonstrating conditional exceptions: an exception clause can reverse the general rule for certain cases.",
  },

  /* ---------------- PART 1 — Problem Solving ---------------- */
  {
    id: "p1-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    sectionTitle: "Listening to Problem Solving",
    bullets: [
      "You will hear a conversation in which two people resolve a complication. You will hear it only once.",
      "Track the conditions and the final agreed plan.",
    ],
  },
  {
    id: "p1-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    instruction: "Listen to a conversation between an employee and an IT support agent. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.customerService,
    script: [
      { speaker: "Employee", text: "Hi, I'm locked out of the shared project drive. I can log into my computer and email fine, but the drive just says 'access denied.' I have a client deliverable due at five." },
      { speaker: "Agent", text: "Okay, let's not panic — five o'clock gives us room. First, this is almost certainly a permissions issue, not a broken account, because you said email and login work. When did you last successfully open the drive?" },
      { speaker: "Employee", text: "Yesterday afternoon it was fine. This morning, nothing." },
      { speaker: "Agent", text: "That timing is the clue. We ran a security migration overnight, and it reset group memberships. Anyone whose manager hadn't re-approved their access by midnight got dropped. So the fix isn't on your end at all — I need your manager to re-approve you in the portal, and then it's instant." },
      { speaker: "Employee", text: "My manager is on a flight until three. That's cutting it close." },
      { speaker: "Agent", text: "Understood. Here's the thing: any team lead can approve, not only your direct manager. Is there another lead on your project who's in the office?" },
      { speaker: "Employee", text: "Yes — Fatima's here, she co-leads the project." },
      { speaker: "Agent", text: "Perfect. Have Fatima approve you; that restores access immediately. But — and this matters — approval only restores your existing folders. If you'd been added to any new folder this week, that would need your actual manager. Were you?" },
      { speaker: "Employee", text: "No, same folders as always." },
      { speaker: "Agent", text: "Then Fatima's approval fully solves it. Go grab her now; you'll be back in within a minute of her clicking approve." },
    ],
    transcript:
      "An employee is locked out of the shared drive but can still log in and use email, so the IT agent identifies it as a permissions issue, not a broken account. An overnight security migration reset group memberships and dropped anyone whose access wasn't re-approved by midnight. The fix is manager re-approval in the portal, which is instant — and crucially, any team lead can approve, not only the direct manager, who is on a flight until three. A co-lead, Fatima, can approve. The agent notes approval only restores existing folders; new folders added this week would need the actual manager — but the employee had no new folders, so Fatima's approval fully solves it.",
  },
  q("p1q1", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "Why is the agent confident the account itself is not broken?",
    ["The employee reset the password.", "Login and email still work, pointing to a permissions issue.", "The drive is offline for everyone.", "The deadline was extended."], 1),
  q("p1q2", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "What actually caused the lockout?",
    ["The employee mistyped a password.", "An overnight security migration reset group memberships.", "The manager deleted the account.", "A power outage in the building."], 1),
  q("p1q3", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "Who exactly gets dropped by the migration?",
    ["Everyone in the company.", "Anyone whose access wasn't re-approved by midnight.", "Only new employees.", "Only people who were on holiday."], 1),
  q("p1q4", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "Why can Fatima solve the problem instead of the direct manager?",
    ["She is more senior.", "Any team lead can approve, not just the direct manager.", "She controls the migration.", "She has the employee's password."], 1),
  q("p1q5", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "Under what condition would Fatima's approval NOT be enough?",
    ["If the deadline were earlier.", "If the employee had been added to a new folder this week.", "If the manager were in the office.", "If email were also down."], 1),
  q("p1q6", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "Why does Fatima's approval fully solve this employee's case?",
    ["The manager already approved earlier.", "The employee only needs existing folders, which approval restores.", "IT reversed the migration.", "The deliverable was cancelled."], 1),

  /* ---------------- PART 2 — Daily Life Conversation ---------------- */
  {
    id: "p2-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    sectionTitle: "Listening to a Daily Life Conversation",
    bullets: [
      "You will hear a conversation between two people. You will hear it only once.",
      "Listen for attitude and what each person actually wants.",
    ],
  },
  {
    id: "p2-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    instruction: "Listen to two neighbours discussing a shared fence. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.dailyConversation,
    script: [
      { speaker: "Rosa", text: "Hi Ken, I've been meaning to catch you. The fence between our yards is leaning pretty badly after that storm. I think it's going to come down." },
      { speaker: "Ken", text: "Yeah, I noticed. Honestly, I've been dreading this conversation, because those fences are expensive and I'm on a tight budget this year." },
      { speaker: "Rosa", text: "I hear you. I'm not suggesting we go for anything fancy. And legally, since it's a shared boundary, the cost is split fifty-fifty — but I'd rather we just agree between ourselves than get anyone official involved." },
      { speaker: "Ken", text: "That's a relief. I was worried you'd want the expensive cedar one your other neighbour put in." },
      { speaker: "Rosa", text: "No, no. A basic treated-pine fence is totally fine for me. My only real preference is that it's tall enough that my dog can't jump it — she's a bit of an escape artist." },
      { speaker: "Ken", text: "Ha, fair. I can live with that. Should we each get a quote and compare?" },
      { speaker: "Rosa", text: "Actually, my brother-in-law does fencing. He'd give us a mate's rate and do a solid job. Would you trust me on that, or would you feel more comfortable getting an independent quote too?" },
      { speaker: "Ken", text: "If he's reliable and it saves us both money, I'm happy to go with him. Just send me the quote before we commit, so I can budget for my half." },
      { speaker: "Rosa", text: "Deal. I'll get the number this week." },
    ],
    transcript:
      "Rosa tells her neighbour Ken their shared fence is leaning after a storm and likely to fall. Ken is anxious because fences are expensive and money is tight. Rosa reassures him she wants only a basic treated-pine fence, not an expensive cedar one, and that the cost is legally split fifty-fifty but she'd rather settle it informally. Her one requirement is that it be tall enough that her escape-artist dog can't jump it. Rosa offers her brother-in-law, a fencer who'd give a discount; Ken agrees provided he sees the quote first so he can budget his half.",
  },
  q("p2q1", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "Why has Ken been 'dreading this conversation'?",
    ["He dislikes Rosa.", "Fences are expensive and he is on a tight budget.", "His dog damaged the fence.", "He wants to remove the fence entirely."], 1),
  q("p2q2", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "What kind of fence does Rosa want?",
    ["An expensive cedar fence.", "A basic treated-pine fence.", "No fence at all.", "A metal fence."], 1),
  q("p2q3", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "What is Rosa's one real requirement?",
    ["That it match the other neighbour's fence.", "That it be tall enough her dog can't jump it.", "That Ken pay more than half.", "That it be finished this week."], 1),
  q("p2q4", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "How does Rosa prefer to handle the cost split?",
    ["By getting officials involved.", "By agreeing informally between themselves.", "By paying the full amount herself.", "By taking Ken to court."], 1),
  q("p2q5", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "What condition does Ken attach to using Rosa's brother-in-law?",
    ["That he be licensed by the city.", "That Ken sees the quote first so he can budget his half.", "That the work be done on a weekend.", "That Rosa pays upfront."], 1),

  /* ---------------- PART 3 — Listening for Information ---------------- */
  {
    id: "p3-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 3: Listening for Information`,
    sectionTitle: "Listening for Information",
    bullets: [
      "You will hear an informational segment. You will hear it only once.",
      "There are steps, numbers, and exceptions — keep them straight.",
    ],
  },
  {
    id: "p3-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 3: Listening for Information`,
    instruction: "Listen to a museum guide briefing a new group of volunteer docents. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.publicTalk,
    script: [
      { speaker: "Guide", text: "Welcome, docents. Your role is to enrich visitors' experience, not to police them, but there are a few firm rules I need you to enforce consistently. First, photography. Visitors may photograph the permanent collection freely, but flash is never permitted, and the touring exhibition on the second floor — the textiles — cannot be photographed at all, because the lenders forbid it. So the rule flips depending on which gallery you're standing in." },
      { speaker: "Guide", text: "Second, the hands-on cart. We keep a cart of replica objects that visitors are actively encouraged to touch — that's the whole point of it. Please don't stop them; that's different from the display cases, which are strictly no-touch. If you see confusion, gently redirect people from the cases to the cart. Third, group size for tours: you can take up to fifteen people, but in the textiles exhibition the limit drops to eight, because the room is small and the humidity controls are sensitive to crowds." },
      { speaker: "Guide", text: "Finally, timing. Tours leave from the lobby on the hour, every hour, from ten to four — so the last tour is at four, not five, even though we close at five. That last hour is deliberately tour-free so we can reset the galleries. If someone arrives at four-thirty wanting a tour, the honest answer is that they've missed the last one, but they're welcome to explore on their own until closing." },
    ],
    transcript:
      "A guide briefs volunteer docents. Photography rules flip by gallery: the permanent collection may be photographed (never with flash), but the second-floor touring textiles exhibition cannot be photographed at all because lenders forbid it. The hands-on cart of replicas is meant to be touched and docents should not stop visitors, unlike the strictly no-touch display cases. Tour groups can be up to fifteen, but only eight in the textiles room due to its size and humidity controls. Tours leave the lobby on the hour from ten to four, so the last tour is at four (not five); the final hour before the 5 p.m. close is tour-free for resetting galleries, though late arrivals may explore alone.",
  },
  q("p3q1", `${HEADER_BASE} Part 3: Listening for Information`,
    "What is the photography rule in the textiles exhibition?",
    ["Photos allowed without flash.", "No photography at all, because lenders forbid it.", "Photos allowed with flash only.", "Same as the permanent collection."], 1),
  q("p3q2", `${HEADER_BASE} Part 3: Listening for Information`,
    "How should docents treat the hands-on cart?",
    ["Stop visitors from touching it.", "Encourage touching, unlike the no-touch display cases.", "Keep it locked.", "Allow touching only during tours."], 1),
  q("p3q3", `${HEADER_BASE} Part 3: Listening for Information`,
    "What is the group-size limit in the textiles room?",
    ["Fifteen.", "Eight.", "Ten.", "No limit."], 1),
  q("p3q4", `${HEADER_BASE} Part 3: Listening for Information`,
    "Why is the textiles group limit lower?",
    ["The exhibition is unpopular.", "The room is small and its humidity controls are sensitive to crowds.", "There are fewer docents.", "Photography slows the group down."], 1),
  q("p3q5", `${HEADER_BASE} Part 3: Listening for Information`,
    "When does the last tour leave?",
    ["At five, when the museum closes.", "At four.", "At four-thirty.", "On the half-hour."], 1),
  q("p3q6", `${HEADER_BASE} Part 3: Listening for Information`,
    "Why is the final hour tour-free?",
    ["Staff go home early.", "So the galleries can be reset before closing.", "It is the busiest hour.", "The textiles room closes early."], 1),

  /* ---------------- PART 4 — News Item ---------------- */
  {
    id: "p4-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 4: Listening to a News Item`,
    sectionTitle: "Listening to a News Item",
    bullets: [
      "You will hear a news report. You will hear it only once.",
      "Separate what is confirmed from what is claimed or still uncertain.",
    ],
  },
  {
    id: "p4-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 4: Listening to a News Item`,
    instruction: "Listen to the news report. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.newsReport,
    script: [
      { speaker: "Anchor", text: "A regional hospital's decision to trial four-day working weeks for its administrative staff is drawing national attention tonight. Under the pilot, non-clinical employees work the same total hours compressed into four longer days, with no cut in pay. Crucially — and this is a point critics often miss — the change applies only to administrative and support roles. Frontline clinical staff, doctors and nurses, are not part of the trial, and the hospital insists patient-facing hours are completely unaffected." },
      { speaker: "Reporter", text: "That distinction is central. Early figures the hospital released suggest administrative sick days have dropped by about a quarter, and staff-satisfaction scores are up. But the administration is careful to call these results 'preliminary and not yet independently verified.' Union representatives welcome the trial but warn it must not become a backdoor to increasing daily workloads. Meanwhile, some patient advocacy groups worry that even administrative changes could indirectly slow things like appointment scheduling. The hospital says it will publish audited results after the six-month mark before deciding whether to make the policy permanent or extend it to other departments." },
    ],
    transcript:
      "A regional hospital is trialling a four-day week for non-clinical staff: the same total hours compressed into four longer days with no pay cut. The change applies only to administrative and support roles — frontline doctors and nurses are excluded, and patient-facing hours are unaffected. Preliminary, not-yet-independently-verified figures show administrative sick days down about a quarter and higher satisfaction. Unions welcome it but warn against increasing daily workloads; some patient advocates worry it could indirectly slow scheduling. The hospital will publish audited results after six months before deciding whether to make it permanent or extend it.",
  },
  q("p4q1", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "What is the four-day-week trial?",
    ["Fewer total hours for all staff.", "The same total hours compressed into four longer days with no pay cut.", "A pay cut in exchange for a day off.", "Extra holidays for clinical staff."], 1),
  q("p4q2", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "Which staff are included in the trial?",
    ["Doctors and nurses.", "Only administrative and support roles.", "All hospital employees.", "Only senior managers."], 1),
  q("p4q3", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "How does the hospital describe its early results?",
    ["Final and fully audited.", "Preliminary and not yet independently verified.", "Disappointing so far.", "Identical to other hospitals."], 1),
  q("p4q4", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "What concern do union representatives raise?",
    ["That pay will be cut.", "That it must not become a way to increase daily workloads.", "That clinical staff are excluded.", "That the trial is too short."], 1),
  q("p4q5", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "What will the hospital do before deciding on permanence?",
    ["Immediately expand it to all departments.", "Publish audited results after the six-month mark.", "Cancel the trial.", "Add clinical staff to the trial."], 1),

  /* ---------------- PART 5 — Academic Discussion ---------------- */
  {
    id: "p5-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 5: Listening to a Discussion`,
    sectionTitle: "Listening to a Discussion",
    bullets: [
      "You will hear an extended discussion among three people. You will hear it only once.",
      "Track each person's position and how the plan evolves.",
    ],
  },
  {
    id: "p5-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 5: Listening to a Discussion`,
    instruction: "Listen to three committee members planning a charity fundraising event. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.campusDiscussion,
    script: [
      { speaker: "Nadia", text: "So last year's gala dinner raised twelve thousand, but honestly, after venue and catering, we only netted about seven. I think we're spending too much to make too little. I'd rather do something leaner this year — maybe an online auction, almost no overhead." },
      { speaker: "Sam", text: "The math is hard to argue with. But the gala isn't only about the money on the night — it's where we sign up our big annual donors. Half of our recurring pledges came from conversations at that dinner. An online auction can't replicate that face-to-face relationship-building." },
      { speaker: "Nadia", text: "That's a genuinely good point. I hadn't weighted the pledges." },
      { speaker: "Grace", text: "What if we don't treat it as either-or? Keep a dinner, but shrink it dramatically — a smaller, invitation-only event for our top twenty donors, far cheaper to run, focused purely on those relationships. Then run the online auction in parallel to reach everyone else and drive volume." },
      { speaker: "Sam", text: "Oh, I like that. The small dinner protects the relationships, the auction protects the reach. And a twenty-person dinner costs a fraction of a two-hundred-person gala." },
      { speaker: "Nadia", text: "I'm sold, with one caveat: we should set a hard cap on the dinner budget this time. Last year it crept up because we kept saying yes to 'just one more' expense." },
      { speaker: "Grace", text: "Agreed — let's cap it at fifteen hundred and refuse anything beyond that. Sam, you're best with the major donors, so you host the dinner. Nadia, you're our digital person, so you run the auction platform. I'll coordinate and keep us on budget." },
      { speaker: "Sam", text: "Deal. And let's agree the auction goes live two weeks before the dinner, so the dinner becomes the closing celebration rather than competing with it." },
      { speaker: "Nadia", text: "Smart. That sequencing actually makes both stronger." },
    ],
    transcript:
      "Three committee members review last year's gala, which grossed twelve thousand but netted only about seven after costs. Nadia wants a lean online auction with little overhead. Sam objects that the gala's real value is signing recurring big donors face-to-face — half their pledges came from it — which an auction can't replicate. Grace proposes doing both: a small, invitation-only dinner for the top twenty donors (much cheaper, relationship-focused) plus a parallel online auction for reach and volume. All agree, with Nadia insisting on a hard budget cap; they set it at fifteen hundred. Roles: Sam hosts the dinner, Nadia runs the auction, Grace coordinates and guards the budget. They also agree the auction goes live two weeks before the dinner so the dinner is a closing celebration rather than a competitor.",
  },
  q("p5q1", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "Why is Nadia dissatisfied with last year's gala?",
    ["It was poorly attended.", "It grossed twelve thousand but netted only about seven after costs.", "The donors complained.", "The venue cancelled."], 1),
  q("p5q2", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What does Sam argue the gala uniquely provides?",
    ["The lowest overhead.", "Face-to-face relationship-building that signs recurring big donors.", "The largest online audience.", "Free catering."], 1),
  q("p5q3", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What is Grace's proposed solution?",
    ["Cancel the dinner entirely.", "A small invitation-only dinner plus a parallel online auction.", "Repeat last year's gala unchanged.", "Only an online auction."], 1),
  q("p5q4", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What caveat does Nadia insist on?",
    ["Inviting more people.", "Setting a hard cap on the dinner budget.", "Holding the event outdoors.", "Hiring a professional host."], 1),
  q("p5q5", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "Why is Sam assigned to host the dinner?",
    ["He volunteered first.", "He is best with the major donors.", "He has the most free time.", "He suggested the idea."], 1),
  q("p5q6", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What is the purpose of the small dinner in the new plan?",
    ["To reach the widest possible audience.", "To protect key donor relationships.", "To replace the auction.", "To cut all costs to zero."], 1),
  q("p5q7", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "Why will the auction go live two weeks before the dinner?",
    ["To sell tickets to the dinner.", "So the dinner becomes a closing celebration rather than competing with the auction.", "Because the platform requires it.", "To give donors time to travel."], 1),
  q("p5q8", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What changed Nadia's mind about keeping a dinner?",
    ["Grace outvoted her.", "Sam's point about donor pledges she hadn't weighted.", "The venue offered a discount.", "The auction platform failed."], 1),

  /* ---------------- PART 6 — Viewpoints ---------------- */
  {
    id: "p6-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    sectionTitle: "Listening to Viewpoints",
    bullets: [
      "You will hear a recorded segment presenting a debate. You will hear it only once.",
      "Identify exactly where the two speakers agree and where they diverge.",
    ],
  },
  {
    id: "p6-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    instruction: "Listen to a segment debating whether students should be allowed to use AI tools for homework. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.interview,
    script: [
      { speaker: "Host", text: "Should students be allowed to use AI writing tools for their homework? With me are teacher Mr. Boyd and education researcher Dr. Sethi. Mr. Boyd, I take it you're against it?" },
      { speaker: "Mr. Boyd", text: "Not a blanket ban, actually — that's a common misreading of my position. My concern is narrower. When a student uses AI to produce a finished essay, they skip the struggle that actually builds skill: organising thoughts, wrestling with a sentence. For foundational assignments, that struggle is the whole point, so there I'd restrict it. But for research or brainstorming, where the thinking still happens in the student's head, I have no objection." },
      { speaker: "Host", text: "Dr. Sethi, you research this. Do you disagree?" },
      { speaker: "Dr. Sethi", text: "Less than you'd think. I agree completely that using AI to bypass foundational skill-building is harmful — the evidence there is clear. Where I'd push Mr. Boyd is on feasibility. Banning it for some assignments assumes we can reliably detect misuse, and honestly, we can't; detection tools are unreliable. So rather than trying to police it, I'd redesign assignments to make AI unhelpful — in-class writing, oral defences, personal reflection that AI can't fake." },
      { speaker: "Mr. Boyd", text: "I actually think that's the stronger version of my own argument. If you can't enforce a rule, redesigning the task is smarter than pretending the rule works." },
      { speaker: "Dr. Sethi", text: "Right. We're not really disagreeing on the danger, or even on foundational skills. We differ only on method — rules versus redesign. And I'd argue redesign is just a more honest way of achieving exactly what he wants." },
      { speaker: "Host", text: "So the real debate isn't whether, but how." },
      { speaker: "Mr. Boyd", text: "Exactly. And I'm coming around to the redesign approach." },
    ],
    transcript:
      "A debate on students using AI for homework. Mr. Boyd, a teacher, does not favour a blanket ban; his concern is narrow — AI shouldn't replace the struggle that builds foundational skills, so he'd restrict it for foundational essays but allow it for research and brainstorming. Dr. Sethi, a researcher, largely agrees that bypassing foundational skill-building is harmful, but pushes back on feasibility: misuse can't be reliably detected, so instead of policing, she'd redesign assignments (in-class writing, oral defences, personal reflection) to make AI unhelpful. Boyd concedes this is a stronger version of his own view. They agree on the danger and on protecting foundational skills, differing only on method — rules versus redesign — with Boyd coming around to redesign.",
  },
  q("p6q1", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "What is Mr. Boyd's actual position?",
    ["A complete ban on AI in schools.", "Restrict AI for foundational assignments but allow it for research and brainstorming.", "Allow AI for everything.", "Ban AI only in exams."], 1),
  q("p6q2", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "Why does Mr. Boyd want to restrict AI on foundational work?",
    ["It is too expensive.", "The struggle of doing it builds skill, and AI removes that struggle.", "It produces poor grammar.", "Parents object to it."], 1),
  q("p6q3", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "On what point does Dr. Sethi agree with Mr. Boyd?",
    ["That AI should be fully banned.", "That bypassing foundational skill-building is harmful.", "That detection tools work well.", "That research use is dangerous."], 1),
  q("p6q4", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "What is Dr. Sethi's main objection to Mr. Boyd's approach?",
    ["It is too lenient.", "Misuse can't be reliably detected, so rules can't be enforced.", "It bans too much.", "It ignores foundational skills."], 1),
  q("p6q5", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "What does Dr. Sethi propose instead of policing AI use?",
    ["Harsher penalties.", "Redesigning assignments so AI is unhelpful.", "Better detection software.", "Banning homework altogether."], 1),
  q("p6q6", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "What best describes the outcome of the discussion?",
    ["They remain sharply opposed.", "They agree on the danger and goal, differing only on method, with Boyd moving toward redesign.", "Dr. Sethi abandons her position.", "They agree AI should be banned entirely."], 1),

  {
    id: "result",
    kind: "result",
    headerTitle: `${HEADER_BASE} Results`,
  },
]

export const listeningTest5: MockTest = {
  id: "listening-5",
  title: "CELPIP Listening — Advanced Practice Test 5",
  section: "listening",
  description:
    "A high-difficulty CELPIP-style Listening test with six parts and longer, denser audio full of conditions, exceptions, and self-corrections: problem solving, a neighbour conversation, a museum briefing, a news report, a fundraising discussion, and an AI-in-schools debate.",
  durationLabel: "45–50 min",
  questionCount: 38,
  steps,
}
