import type { MockTest, TestStep } from "./types"
import { LISTENING_BLUEPRINT } from "./listening-blueprint"

const HEADER_BASE = "Advanced Mock Exam 6 - Listening"

function q(
  id: string,
  header: string,
  prompt: string,
  options: [string, string, string, string],
  correctIndex: number,
): TestStep {
  return {
    id,
    kind: "audio-mcq",
    headerTitle: header,
    instruction: "Listen to the question. You will hear it only once.",
    answerSeconds: 30,
    script: [{ text: prompt }],
    question: {
      id,
      prompt,
      correctOptionId: `${id}-${correctIndex}`,
      options: options.map((text, i) => ({ id: `${id}-${i}`, text })),
    },
  }
}

const steps: TestStep[] = [
  {
    id: "intro",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} - CELPIP Test`,
    sectionTitle: "Listening Test Instructions",
    bullets: [
      "This advanced Listening section uses longer clips, faster natural speech, and speakers who qualify, hedge, and revise what they say.",
      "You will hear each clip only once. The correct answer often depends on a single conditional phrase — 'unless', 'only if', 'except', 'provided that'.",
      "Expect distractors that repeat exact words from the audio but attach them to the wrong idea.",
      "There are six parts and 38 questions in total.",
    ],
  },
  {
    id: "video",
    kind: "video",
    headerTitle: `${HEADER_BASE} - Instructional Video`,
    heading: "Listening Video Instructions",
    posterSrc: "/mock-test/listening-video-poster.png",
    narration:
      "Welcome to Advanced Mock Exam 6. This Listening section is the most demanding in the set. Speakers will change their minds mid-sentence, attach conditions to what they say, and use tone to signal meaning that the words alone do not carry. Listen all the way to the end of each turn before deciding. When you are ready, select Next to begin.",
  },
  {
    id: "practice",
    kind: "audio",
    headerTitle: `${HEADER_BASE} - Practice Task`,
    instruction: "Practice Task: Check your headphones. You will hear a short sample.",
    script: [
      { text: "This is a sound check. Listen for the reversal: 'I was going to drive, but with the road closures I'll take the train instead.' The final decision is the train, not the car. Adjust your volume, then select Next to begin." },
    ],
    transcript:
      "A sound check demonstrating a mid-sentence reversal: the speaker's final decision replaces the one stated first.",
  },

  /* ---------------- PART 1 — Problem Solving ---------------- */
  {
    id: "p1-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    sectionTitle: "Listening to Problem Solving",
    bullets: [
      "You will hear a conversation in which two people resolve a complication. You will hear it only once.",
      "Track the conditions and the final agreed plan.",
    ],
  },
  {
    id: "p1-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    instruction: "Listen to a conversation between a traveller and an airline service agent. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.customerService,
    script: [
      { speaker: "Traveller", text: "Hi. My connecting flight was cancelled and I've been rebooked, but the new itinerary has me arriving a full day late, and I have a wedding I'm supposed to be at tomorrow evening. Is there anything faster?" },
      { speaker: "Agent", text: "Let me look. Okay — I can see the cancellation was weather-related, which matters, because it changes what I'm able to offer. If it had been our fault, I could rebook you on another airline for free. For weather, I can still move you, but only onto our own flights unless you're willing to pay a fare difference." },
      { speaker: "Traveller", text: "I'd rather not pay if I can avoid it. What are my options on your airline?" },
      { speaker: "Agent", text: "There's a seat on a flight tonight at nine, connecting through Denver, that would get you in by tomorrow at eleven a.m. — plenty of time for an evening wedding. The catch is that it's standby for the Denver leg; it's very likely, but not guaranteed." },
      { speaker: "Traveller", text: "Hmm. And if standby doesn't clear?" },
      { speaker: "Agent", text: "Then you'd be back on tomorrow's confirmed flight — the same late arrival you have now, so you're no worse off than your current booking. You're only risking time you'd otherwise be sitting in the airport anyway." },
      { speaker: "Traveller", text: "When you put it that way, there's really no downside. Let's do the standby." },
      { speaker: "Agent", text: "Good choice. One thing — because you're choosing standby voluntarily, if it doesn't clear I can't offer a hotel voucher; those only apply when we can't get you out at all. Are you okay with that?" },
      { speaker: "Traveller", text: "Yes, that's fair. Book the standby." },
    ],
    transcript:
      "A traveller's connection was cancelled and rebooked a day late, threatening a wedding. The agent explains the cause matters: a weather cancellation (not the airline's fault) means free rebooking only on the airline's own flights unless the traveller pays a fare difference. The best option is a nine p.m. flight through Denver arriving 11 a.m. next day — but the Denver leg is standby, likely but not guaranteed. If standby fails, the traveller reverts to the same late confirmed flight, so there's no real downside beyond airport waiting time. The traveller agrees. The agent adds one condition: because standby is voluntary, no hotel voucher applies if it doesn't clear, since vouchers only apply when they can't get the traveller out at all. The traveller accepts.",
  },
  q("p1q1", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "Why does the cause of the cancellation matter to the agent's options?",
    ["Weather cancellations cost more to fix.", "For weather, free rebooking is limited to the airline's own flights unless a fare difference is paid.", "Weather cancellations cannot be rebooked.", "The airline's fault means no rebooking."], 1),
  q("p1q2", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "What is the main risk of the nine p.m. option?",
    ["The whole flight is standby.", "The Denver leg is standby — likely but not guaranteed.", "It arrives after the wedding.", "It requires paying a fare difference."], 1),
  q("p1q3", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "What happens if the standby does not clear?",
    ["The traveller is stranded overnight.", "The traveller reverts to the same late confirmed flight, no worse off.", "The traveller must buy a new ticket.", "The traveller loses the booking entirely."], 1),
  q("p1q4", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "Why does the traveller conclude there is 'no downside'?",
    ["The flight is free of charge.", "They only risk airport waiting time they'd have anyway.", "The wedding was cancelled.", "The agent guaranteed the seat."], 1),
  q("p1q5", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "Under what condition would a hotel voucher be provided?",
    ["Whenever standby fails.", "Only when the airline cannot get the traveller out at all.", "For all weather cancellations.", "If the traveller pays a fare difference."], 1),
  q("p1q6", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "Why does no hotel voucher apply to this traveller if standby fails?",
    ["They already have a hotel.", "Because they chose standby voluntarily.", "Vouchers are never offered.", "The flight was the airline's fault."], 1),

  /* ---------------- PART 2 — Daily Life Conversation ---------------- */
  {
    id: "p2-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    sectionTitle: "Listening to a Daily Life Conversation",
    bullets: [
      "You will hear a conversation between two people. You will hear it only once.",
      "Listen for attitude and what each person actually wants.",
    ],
  },
  {
    id: "p2-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    instruction: "Listen to two friends discussing a joint holiday. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.dailyConversation,
    script: [
      { speaker: "Tom", text: "So, about the trip — I've been looking at the mountain cabin idea you sent. It looks gorgeous, but I'll be honest, I was hoping for something a bit more active. A week of just sitting by a lake might drive me a little stir-crazy." },
      { speaker: "Leah", text: "Okay, that's useful to know. I picked it mostly because it's cheap and quiet — I really need to switch off this year, work's been relentless. But I don't want you bored the whole time either." },
      { speaker: "Tom", text: "What if we compromise? The same region has loads of hiking trails and a whitewater rafting outfit. We could keep the cabin as a base — you get your quiet mornings — and I do a couple of active day trips. You wouldn't have to join those." },
      { speaker: "Leah", text: "Oh, I'd actually be up for the hiking, just not the rafting — that sounds terrifying to me. As long as I'm not being dragged onto a raft, I'm happy." },
      { speaker: "Tom", text: "Deal. I'll do the rafting solo or find a group tour. Hiking we do together." },
      { speaker: "Leah", text: "Perfect. One condition though — can we agree that at least two full days are completely unplanned? I don't want this to become a packed itinerary where I need a holiday to recover from the holiday." },
      { speaker: "Tom", text: "Ha, absolutely. Two do-nothing days, minimum. I'll book the cabin tonight if you send me the dates." },
      { speaker: "Leah", text: "Sending them now. This actually sounds like the best of both worlds." },
    ],
    transcript:
      "Tom likes Leah's mountain-cabin idea but wants a more active holiday, fearing boredom. Leah chose it for being cheap and quiet because she badly needs to switch off after a relentless work period. They compromise: keep the cabin as a base so Leah gets quiet mornings, while Tom does active day trips she needn't join. Leah is happy to hike together but refuses the whitewater rafting, which Tom will do solo or with a group. Leah adds one condition — at least two completely unplanned 'do-nothing' days so the trip isn't over-scheduled. Tom agrees and will book the cabin once she sends dates.",
  },
  q("p2q1", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "Why is Tom hesitant about the cabin?",
    ["It is too expensive.", "He wanted a more active holiday and fears boredom.", "It is too far away.", "He dislikes lakes."], 1),
  q("p2q2", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "Why did Leah choose the cabin?",
    ["It is close to rafting.", "It is cheap and quiet, and she needs to switch off after hard work.", "Tom suggested it.", "It has many activities."], 1),
  q("p2q3", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "Which activity is Leah willing to do with Tom?",
    ["Whitewater rafting.", "Hiking.", "Nothing outdoors.", "A packed itinerary of tours."], 1),
  q("p2q4", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "What is the compromise they reach?",
    ["Cancel the cabin and go somewhere active.", "Keep the cabin as a base; Tom does active day trips Leah needn't join.", "Only do quiet activities.", "Split up for the week."], 1),
  q("p2q5", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "What condition does Leah attach to the plan?",
    ["That Tom pay for the cabin.", "That at least two full days stay completely unplanned.", "That they leave early.", "That they invite more friends."], 1),

  /* ---------------- PART 3 — Listening for Information ---------------- */
  {
    id: "p3-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 3: Listening for Information`,
    sectionTitle: "Listening for Information",
    bullets: [
      "You will hear an informational segment. You will hear it only once.",
      "There are steps, numbers, and exceptions — keep them straight.",
    ],
  },
  {
    id: "p3-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 3: Listening for Information`,
    instruction: "Listen to a coordinator briefing new participants in a city bike-share program. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.publicTalk,
    script: [
      { speaker: "Coordinator", text: "Welcome to the bike-share orientation. Let me walk you through how billing and returns work, because a few rules trip people up. First, the pricing. Your membership includes unlimited rides under thirty minutes — that's the key number. Anything over thirty minutes on a single trip adds a fee, and it climbs the longer you hold the bike. So the trick regular users learn is to dock the bike and immediately take out another one; that resets your clock and stays free." },
      { speaker: "Coordinator", text: "Second, docking. A ride only ends when the light on the dock turns green. If you leave without checking, and the bike wasn't locked in properly, the trip keeps running and you'll be charged — and in the worst case, charged for a lost bike. So always wait for the green light. It takes two seconds and saves a lot of grief." },
      { speaker: "Coordinator", text: "Third, availability. If a station is completely full when you arrive, don't just leave the bike leaning against it — that still counts as not returned. Instead, use the app to find the nearest station with space, and here's the useful part: if the app directs you to a fuller-than-expected station, it gives you fifteen extra free minutes to get to another one. But that grace period only activates if you request it through the app first, not automatically." },
      { speaker: "Coordinator", text: "Finally, faults. If a bike has a mechanical problem, dock it and press the wrench button on the dock to report it. That flags the bike as out of service and, importantly, refunds that trip. If you just dock it silently, the next rider inherits the problem and you don't get the refund." },
    ],
    transcript:
      "A bike-share coordinator explains billing and returns. Membership includes unlimited rides under thirty minutes; trips over thirty minutes incur a fee that rises with time, so regulars dock and immediately take another bike to reset the clock for free. A ride only ends when the dock light turns green; leaving without checking can mean continued charges or a lost-bike charge. If a station is full, don't leave the bike leaning (it counts as not returned) — use the app to find space, and requesting redirection through the app first grants fifteen extra free minutes (it doesn't activate automatically). For a faulty bike, dock it and press the wrench button to report it, which flags it out of service and refunds the trip; docking silently forfeits the refund and passes the problem on.",
  },
  q("p3q1", `${HEADER_BASE} Part 3: Listening for Information`,
    "What is the key time limit for free rides?",
    ["Fifteen minutes.", "Thirty minutes per single trip.", "Sixty minutes.", "There is no limit."], 1),
  q("p3q2", `${HEADER_BASE} Part 3: Listening for Information`,
    "How do regular users avoid overage fees on long journeys?",
    ["They pay a flat daily rate.", "They dock and immediately take another bike to reset the clock.", "They ride slower.", "They ask for a refund each time."], 1),
  q("p3q3", `${HEADER_BASE} Part 3: Listening for Information`,
    "How can a rider be sure a trip has ended?",
    ["The app sends a text.", "The light on the dock turns green.", "The bike beeps twice.", "They lock it with their own lock."], 1),
  q("p3q4", `${HEADER_BASE} Part 3: Listening for Information`,
    "What should you do if a station is completely full?",
    ["Leave the bike leaning against it.", "Use the app to find a station with space.", "Wait until someone leaves.", "Take the bike home."], 1),
  q("p3q5", `${HEADER_BASE} Part 3: Listening for Information`,
    "How do you get the fifteen extra free minutes when a station is full?",
    ["It activates automatically.", "You must request redirection through the app first.", "You call the coordinator.", "You press the wrench button."], 1),
  q("p3q6", `${HEADER_BASE} Part 3: Listening for Information`,
    "What does pressing the wrench button on a faulty bike do?",
    ["Locks the bike permanently.", "Flags it out of service and refunds that trip.", "Charges a repair fee.", "Extends the free time."], 1),

  /* ---------------- PART 4 — News Item ---------------- */
  {
    id: "p4-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 4: Listening to a News Item`,
    sectionTitle: "Listening to a News Item",
    bullets: [
      "You will hear a news report. You will hear it only once.",
      "Separate what is confirmed from what is claimed or still uncertain.",
    ],
  },
  {
    id: "p4-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 4: Listening to a News Item`,
    instruction: "Listen to the news report. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.newsReport,
    script: [
      { speaker: "Anchor", text: "A pilot program that lets residents vote directly on how a slice of the city budget is spent — so-called 'participatory budgeting' — is being called a modest success by the city, though the picture is more nuanced than the headline suggests. Under the scheme, residents of three neighbourhoods proposed and then voted on local projects, with two million dollars set aside." },
      { speaker: "Reporter", text: "Here's what's confirmed: turnout for the vote was higher than for the last municipal election, and the winning projects — mostly park upgrades and safer crossings — are already being built. What's less clear is whether the enthusiasm will last. Critics point out that the two million represents well under one percent of the total budget, so they argue the exercise, while genuine, is largely symbolic. Supporters counter that the real value isn't the money but the civic engagement — residents learning how budgets actually work. The city says it will expand the program to five more neighbourhoods next year, but only if an independent evaluation, due in the spring, confirms that participation was broad rather than dominated by a small, organised group. That last point is the one to watch: early observers worry the same active residents drove most of the vote."},
    ],
    transcript:
      "A participatory-budgeting pilot let residents of three neighbourhoods propose and vote on local projects, with two million dollars set aside. Confirmed: turnout beat the last municipal election, and winning projects (park upgrades, safer crossings) are already being built. Less clear is whether enthusiasm will last. Critics note the two million is well under one percent of the budget, calling the exercise largely symbolic; supporters say the real value is civic engagement and learning how budgets work. The city will expand to five more neighbourhoods next year, but only if a spring independent evaluation confirms participation was broad rather than dominated by a small organised group — a concern early observers already raise.",
  },
  q("p4q1", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "What is 'participatory budgeting' in this report?",
    ["A tax on residents.", "Residents proposing and voting on how a slice of the budget is spent.", "A city audit.", "A new election system for council."], 1),
  q("p4q2", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "Which fact about the program is confirmed?",
    ["It failed to attract voters.", "Turnout beat the last municipal election and winning projects are being built.", "It replaced the city council.", "It cost nothing."], 1),
  q("p4q3", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "Why do critics call the exercise 'largely symbolic'?",
    ["No projects were built.", "The two million is well under one percent of the total budget.", "No one voted.", "The city ignored the results."], 1),
  q("p4q4", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "What do supporters say is the real value of the program?",
    ["The amount of money spent.", "Civic engagement and residents learning how budgets work.", "Lower taxes.", "Faster construction."], 1),
  q("p4q5", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "On what condition will the city expand the program?",
    ["If more money is found.", "If a spring evaluation confirms participation was broad, not dominated by a small group.", "If turnout falls.", "If critics approve."], 1),

  /* ---------------- PART 5 — Discussion ---------------- */
  {
    id: "p5-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 5: Listening to a Discussion`,
    sectionTitle: "Listening to a Discussion",
    bullets: [
      "You will hear an extended discussion among three people. You will hear it only once.",
      "Track each person's position and how the plan evolves.",
    ],
  },
  {
    id: "p5-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 5: Listening to a Discussion`,
    instruction: "Listen to three coworkers deciding how to run their team's new hybrid meetings. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.campusDiscussion,
    script: [
      { speaker: "Owen", text: "So the problem with our hybrid meetings is obvious: the people in the room dominate, and the remote folks can barely get a word in. I think we should just go fully remote for team meetings — everyone on their own screen, level playing field." },
      { speaker: "Priya", text: "I get the fairness argument, and honestly the remote experience is bad right now. But going fully remote throws away the one thing the office is good for — the spontaneous stuff, people staying after to hash out an idea. We'd be solving one problem by creating another." },
      { speaker: "Owen", text: "Fair. I don't love losing that either." },
      { speaker: "Dan", text: "What if the issue isn't remote-versus-in-person, but the format? When I ran meetings at my old company, we had one rule: whoever's in the room still joins the video call on their own laptop, muted, so everyone's a 'tile.' Suddenly the remote people aren't second-class. And we kept a strict speaking order for the first ten minutes so the loud voices couldn't steamroll." },
      { speaker: "Priya", text: "Oh, that's clever — you keep the office benefits but remove the imbalance. I'd add one thing: a shared doc where people drop points in advance, so quieter folks and remote folks have a way in that doesn't depend on interrupting." },
      { speaker: "Owen", text: "Okay, I'm convinced that's better than my nuke-it-from-orbit idea. So: everyone joins as a tile, speaking order for the first ten minutes, and an agenda doc beforehand." },
      { speaker: "Dan", text: "Right. And let's trial it for a month before deciding — if the imbalance is still there, then we revisit Owen's full-remote option as a fallback." },
      { speaker: "Priya", text: "Agreed. Dan, since you've run this format, you set up the first meeting. I'll make the agenda template. Owen, you watch for whether remote people actually speak more — you're the one who cares most about that metric." },
      { speaker: "Owen", text: "Deal. I'll track speaking time and report back after the month." },
    ],
    transcript:
      "Three coworkers tackle unequal hybrid meetings where in-room people dominate. Owen initially wants fully remote meetings for fairness. Priya agrees the remote experience is poor but warns that going fully remote sacrifices valuable spontaneous office collaboration. Dan reframes it as a format problem: have everyone — including those in the room — join the video call as their own muted 'tile,' plus a strict speaking order for the first ten minutes so loud voices can't steamroll. Priya adds a shared agenda doc where people add points in advance, giving quieter and remote people a way in. Owen is convinced this beats his idea. They'll trial it for a month, keeping full-remote as a fallback if imbalance persists. Roles: Dan sets up the first meeting, Priya makes the agenda template, and Owen tracks whether remote people speak more.",
  },
  q("p5q1", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What is Owen's initial proposal?",
    ["Keep meetings exactly as they are.", "Make team meetings fully remote for fairness.", "Ban remote workers from meetings.", "Hold meetings less often."], 1),
  q("p5q2", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What is Priya's objection to going fully remote?",
    ["It costs too much.", "It sacrifices valuable spontaneous office collaboration.", "Remote work is always better.", "It excludes managers."], 1),
  q("p5q3", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What is the core of Dan's alternative idea?",
    ["Cancel video calls entirely.", "Everyone joins as their own muted 'tile,' with a speaking order for the first ten minutes.", "Only managers speak first.", "Meet in a bigger room."], 1),
  q("p5q4", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What does Priya add to Dan's proposal?",
    ["A ban on interruptions.", "A shared agenda doc where people add points in advance.", "Shorter meetings.", "A rotating chairperson."], 1),
  q("p5q5", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What is kept as a fallback option?",
    ["Cancelling all meetings.", "Owen's full-remote idea, if imbalance persists after the trial.", "Returning to the office full time.", "Hiring a facilitator."], 1),
  q("p5q6", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "How long will they trial the new format before deciding?",
    ["One week.", "One month.", "Three months.", "A year."], 1),
  q("p5q7", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "Why is Owen assigned to track speaking time?",
    ["He has the most free time.", "He cares most about whether remote people speak more.", "He proposed the tiles idea.", "He runs the meetings."], 1),
  q("p5q8", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What changed Owen's mind about his original idea?",
    ["Priya outvoted him.", "Dan's format keeps office benefits while removing the imbalance.", "The office closed.", "Remote work was banned."], 1),

  /* ---------------- PART 6 — Viewpoints ---------------- */
  {
    id: "p6-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    sectionTitle: "Listening to Viewpoints",
    bullets: [
      "You will hear a recorded segment presenting a debate. You will hear it only once.",
      "Identify exactly where the two speakers agree and where they diverge.",
    ],
  },
  {
    id: "p6-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    instruction: "Listen to a segment debating whether professional sports teams should be publicly funded. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.interview,
    script: [
      { speaker: "Host", text: "Should cities use public money to build stadiums for professional sports teams? With me are economist Dr. Alvarez and sports columnist Mr. Reed. Dr. Alvarez, you've studied this — I assume you're opposed?" },
      { speaker: "Dr. Alvarez", text: "Opposed to how it's usually done, yes — but let me be precise, because my position is often caricatured. The economic evidence is overwhelming that stadiums don't generate the broad growth cities are promised; the jobs are seasonal and low-wage, and spending is just diverted from other local entertainment. What I'm not saying is that there's no value in a team. There's real civic and cultural value — I just don't think taxpayers should shoulder the construction cost for a privately owned, highly profitable business." },
      { speaker: "Host", text: "Mr. Reed, you write about the cultural side. Do you disagree?" },
      { speaker: "Mr. Reed", text: "On the economics, honestly, no — Dr. Alvarez is right, and it's a bit embarrassing how often teams recycle those inflated projections. Where I'd push her is on the word 'value.' A team can anchor a city's identity in a way that's genuinely hard to price. That said — and this is important — that's an argument for the team, not necessarily for the public paying for the building. I think the two can be separated." },
      { speaker: "Dr. Alvarez", text: "Which is exactly my point. If a city wants to invest in identity, there are cheaper ways than a half-billion-dollar stadium — support youth leagues, public spaces. And if the team is as profitable as its owners claim, they can finance their own facility, perhaps with the city contributing only to genuinely public infrastructure around it, like transit." },
      { speaker: "Mr. Reed", text: "I can live with that framing entirely. Public transit and public spaces, yes; a blank cheque for a private stadium, no. We really only differ on tone — I'm a little more sentimental about the teams than she is." },
      { speaker: "Host", text: "So you agree far more than you disagree." },
      { speaker: "Dr. Alvarez", text: "We do. The disagreement is mostly emotional temperature, not substance." },
    ],
    transcript:
      "A debate on public funding for sports stadiums. Dr. Alvarez, an economist, opposes the usual approach: evidence shows stadiums don't deliver promised broad growth (jobs are seasonal/low-wage, spending is merely diverted), so taxpayers shouldn't fund construction for a profitable private business — though she concedes a team has real civic and cultural value. Mr. Reed, a columnist, agrees on the economics and admits teams recycle inflated projections, but stresses a team's hard-to-price role in city identity. Crucially he separates that from paying for the building. Alvarez agrees: invest in identity more cheaply (youth leagues, public spaces), let profitable owners fund their own facility, with the city contributing only to genuinely public infrastructure like transit. Reed accepts this entirely; they conclude they differ mainly in emotional tone, not substance.",
  },
  q("p6q1", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "What is Dr. Alvarez's precise position?",
    ["Teams have no value at all.", "Taxpayers shouldn't fund stadium construction for a profitable private business, though a team has cultural value.", "Cities should ban professional teams.", "Stadiums always boost the economy."], 1),
  q("p6q2", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "What does the economic evidence show, according to Dr. Alvarez?",
    ["Stadiums create broad, lasting growth.", "Stadiums don't generate promised growth; jobs are seasonal and spending is diverted.", "Stadiums lower city taxes.", "Stadiums pay for themselves quickly."], 1),
  q("p6q3", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "On what point does Mr. Reed agree with Dr. Alvarez?",
    ["That teams have no cultural value.", "On the economics — teams recycle inflated projections.", "That the city should pay for the stadium.", "That stadiums should be larger."], 1),
  q("p6q4", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "What distinction does Mr. Reed insist on?",
    ["Between winning and losing teams.", "Between an argument for the team and an argument for the public paying for the building.", "Between old and new stadiums.", "Between football and baseball."], 1),
  q("p6q5", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "What does Dr. Alvarez say the city could legitimately fund?",
    ["The entire stadium.", "Genuinely public infrastructure around it, like transit.", "The team's payroll.", "Nothing at all."], 1),
  q("p6q6", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "What best describes the outcome of the discussion?",
    ["They remain sharply opposed.", "They agree far more than they disagree, differing mainly in emotional tone.", "Mr. Reed abandons his view of teams' value.", "They agree the city should pay in full."], 1),

  {
    id: "result",
    kind: "result",
    headerTitle: `${HEADER_BASE} Results`,
  },
]

export const listeningTest6: MockTest = {
  id: "listening-6",
  title: "CELPIP Listening — Advanced Practice Test 6",
  section: "listening",
  description:
    "The most demanding CELPIP-style Listening test in the set, with six parts and long, dense audio full of conditions, reversals, and hedging: an airline rebooking, a holiday negotiation, a bike-share briefing, a participatory-budgeting news item, a hybrid-meetings discussion, and a stadium-funding debate.",
  durationLabel: "45–50 min",
  questionCount: 38,
  steps,
}
