import type { MockTest, TestStep } from "./types"
import { LISTENING_BLUEPRINT } from "./listening-blueprint"

const HEADER_BASE = "Advanced Mock Exam 4 - Listening"

function q(
  id: string,
  header: string,
  prompt: string,
  options: [string, string, string, string],
  correctIndex: number,
): TestStep {
  return {
    id,
    kind: "audio-mcq",
    headerTitle: header,
    instruction: "Listen to the question. You will hear it only once.",
    answerSeconds: 30,
    script: [{ text: prompt }],
    question: {
      id,
      prompt,
      correctOptionId: `${id}-${correctIndex}`,
      options: options.map((text, i) => ({ id: `${id}-${i}`, text })),
    },
  }
}

const steps: TestStep[] = [
  {
    id: "intro",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} - CELPIP Test`,
    sectionTitle: "Listening Test Instructions",
    bullets: [
      "This is an advanced simulation calibrated well above a standard practice test. The audio is longer and denser, speakers talk at a natural-to-fast pace, and many questions require inference rather than direct recall.",
      "You will hear each audio clip only once. Take notes — you cannot rewind.",
      "Several answer choices will paraphrase information that was actually stated but does not answer the question. Choose the option that is both accurate and relevant.",
      "There are six parts and 38 questions in total.",
    ],
  },
  {
    id: "video",
    kind: "video",
    headerTitle: `${HEADER_BASE} - Instructional Video`,
    heading: "Listening Video Instructions",
    posterSrc: "/mock-test/listening-video-poster.png",
    narration:
      "Welcome to Advanced Mock Exam 4. This Listening section is intentionally demanding. You will hear a problem-solving conversation, a daily-life conversation, an information segment, a news report, an extended academic discussion, and a set of contrasting viewpoints. Speakers use idiomatic language, qualify their statements, and sometimes correct themselves, so listen for the final position rather than the first thing said. When you are ready, select Next to begin.",
  },
  {
    id: "practice",
    kind: "audio",
    headerTitle: `${HEADER_BASE} - Practice Task`,
    instruction: "Practice Task: Check your headphones. You will hear a short sample.",
    script: [
      { text: "This is a sound check. Notice that the speaker may pause, hesitate, or rephrase — for example, 'The deadline is Thursday; actually, no, they pushed it to Friday.' On this test the corrected information is what counts. Adjust your volume, then select Next to begin." },
    ],
    transcript:
      "A sound check that also demonstrates self-correction: when a speaker revises what they said, the revised statement is the one that counts.",
  },

  /* ---------------- PART 1 — Problem Solving ---------------- */
  {
    id: "p1-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    sectionTitle: "Listening to Problem Solving",
    bullets: [
      "You will hear a conversation in which people work through a complication. You will hear it only once.",
      "Watch for changes of plan, conditions, and who is responsible for what.",
    ],
  },
  {
    id: "p1-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    instruction:
      "Listen to the conversation between a customer and a travel agent. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.customerService,
    script: [
      { speaker: "Customer", text: "Hi — I booked the Lisbon-and-Porto package through you back in March, departure on the ninth. I just got an email saying my connecting flight in Frankfurt has been cancelled, and honestly I'm a bit lost about what it means for the rest of the trip." },
      { speaker: "Agent", text: "Let me pull it up. Right, I see it. So the cancellation is only the Frankfurt-to-Lisbon leg. Your first flight, the transatlantic one, is untouched, and so is everything on the ground — the hotels, the Douro valley tour, the return. What we need to solve is just getting you from Frankfurt into Portugal on the ninth so the rest doesn't unravel." },
      { speaker: "Customer", text: "Okay, that's a relief. So what are my options?" },
      { speaker: "Agent", text: "Two, really. Option one: I rebook you on the airline's own alternative, which routes you through Munich instead. It gets you to Lisbon at nine-forty in the evening — about five hours later than planned, but same day, no extra cost, and it protects your original hotel booking. Option two: I put you on a direct partner flight from Frankfurt, which actually lands earlier, at four in the afternoon, but it lands in Porto rather than Lisbon." },
      { speaker: "Customer", text: "Wait — but my hotel the first two nights is in Lisbon, right? So if I fly into Porto I'd have to get down to Lisbon somehow." },
      { speaker: "Agent", text: "Exactly, and that's the catch. The train from Porto to Lisbon is about three hours, so you'd land at four but not reach your Lisbon hotel until late anyway — and you'd be paying for the train yourself. So the Porto option only makes sense if you'd rather start in the north." },
      { speaker: "Customer", text: "Hmm. Actually — could I just flip the itinerary? Do Porto first, then Lisbon? I'm doing both cities anyway." },
      { speaker: "Agent", text: "You could, but the Douro tour is booked out of Porto for the twelfth, and your Lisbon hotel is prepaid and non-refundable for the ninth and tenth. Rearranging would mean forfeiting those two nights. So it'd cost you more than the train would." },
      { speaker: "Customer", text: "Right. Then let's not do that. I'll take the Munich reroute — later is fine as long as I'm not losing money or nights." },
      { speaker: "Agent", text: "Smart choice. I'll confirm the Munich connection now and email you the updated boarding passes within the hour. Everything else stays exactly as booked." },
    ],
    transcript:
      "A traveller learns that only the Frankfurt-to-Lisbon connecting flight was cancelled; the transatlantic flight, hotels, and Douro tour are intact. The agent offers two fixes: a same-day reroute via Munich arriving five hours late at no cost and keeping the Lisbon hotel, or an earlier direct flight into Porto, which would force a self-paid three-hour train and a late arrival anyway. Flipping the itinerary to start in Porto would forfeit two prepaid, non-refundable Lisbon nights and clash with the Douro tour date. The customer chooses the Munich reroute to avoid extra cost and lost nights.",
  },
  q("p1q1", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "What exactly was cancelled?",
    ["The entire Portugal package.", "Only the Frankfurt-to-Lisbon connecting flight.", "The transatlantic flight from home.", "The Douro valley tour."], 1),
  q("p1q2", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "What is the main drawback of the Munich reroute?",
    ["It costs extra money.", "It arrives about five hours later than planned.", "It cancels the hotel booking.", "It lands in the wrong country."], 1),
  q("p1q3", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "Why is landing earlier in Porto not as helpful as it first sounds?",
    ["The Porto flight is more expensive.", "The customer would still reach the Lisbon hotel late after a self-paid three-hour train.", "The Porto airport is closed in the evening.", "The Douro tour would have to be cancelled."], 1),
  q("p1q4", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "Why does the agent advise against reversing the itinerary?",
    ["The trains to Porto are fully booked.", "It would forfeit two prepaid, non-refundable Lisbon nights and clash with the tour date.", "The customer has never been to Porto.", "The northern hotels cost more."], 1),
  q("p1q5", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "What does the customer care about most in making the decision?",
    ["Arriving as early as possible.", "Not losing money or prepaid nights.", "Seeing Porto before Lisbon.", "Avoiding German airports."], 1),
  q("p1q6", `${HEADER_BASE} Part 1: Listening to Problem Solving`,
    "What will the agent do next?",
    ["Refund the whole package.", "Confirm the Munich connection and email updated boarding passes within the hour.", "Book a train ticket from Porto.", "Cancel the Lisbon hotel."], 1),

  /* ---------------- PART 2 — Daily Life Conversation ---------------- */
  {
    id: "p2-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    sectionTitle: "Listening to a Daily Life Conversation",
    bullets: [
      "You will hear a conversation between two people. You will hear it only once.",
      "Pay attention to feelings, hints, and what is implied but not stated directly.",
    ],
  },
  {
    id: "p2-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    instruction: "Listen to the conversation between two colleagues after work. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.dailyConversation,
    script: [
      { speaker: "Priya", text: "You've been quiet since the two o'clock meeting. Everything alright?" },
      { speaker: "Daniel", text: "Yeah, I'm fine. Well — not entirely. Marcus took the lead on the client pitch, the one I've basically been building for three weeks, and I only found out when he opened the deck this afternoon." },
      { speaker: "Priya", text: "Oh. That's… awkward. Did he say why?" },
      { speaker: "Daniel", text: "He said the director asked him to. Which might be true — I'm not accusing anyone of anything. It's more that nobody thought to mention it to me first. I'd have been fine presenting alongside him. It's the being kept in the dark part that stings." },
      { speaker: "Priya", text: "That's fair. Are you going to say something?" },
      { speaker: "Daniel", text: "I don't want to come across as territorial, especially not right before a big client meeting. But I also don't want this to become the norm. I think I'll wait until after the pitch lands, then have a calm word with the director — not Marcus. It's not really Marcus's fault." },
      { speaker: "Priya", text: "That sounds mature. For what it's worth, everyone knows that deck is yours. The formatting alone gives it away." },
      { speaker: "Daniel", text: "Ha. Thanks. I just needed to hear that I'm not overreacting." },
      { speaker: "Priya", text: "You're not. And honestly, raising it with the director rather than sulking will probably work in your favour." },
    ],
    transcript:
      "Daniel is quietly upset because a colleague, Marcus, took the lead on a client pitch Daniel spent three weeks building, and Daniel wasn't told in advance. He is bothered less by who presents than by being kept in the dark, and he explicitly does not blame Marcus, since a director apparently made the call. He decides to wait until after the pitch and then raise it calmly with the director. Priya reassures him he isn't overreacting and that speaking up will reflect well on him.",
  },
  q("p2q1", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "What is really bothering Daniel?",
    ["That Marcus is a weaker presenter.", "That he was not told in advance about the change.", "That the client meeting was cancelled.", "That he did not finish the deck."], 1),
  q("p2q2", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "Who does Daniel hold responsible for the situation?",
    ["Marcus, for being ambitious.", "Neither Marcus specifically — he sees it as a communication failure.", "Priya, for not warning him.", "The client, for requesting the change."], 1),
  q("p2q3", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "Why does Daniel decide to wait before raising the issue?",
    ["He hopes the problem will disappear.", "He doesn't want to seem territorial right before an important pitch.", "He is too angry to speak.", "He plans to quit instead."], 1),
  q("p2q4", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "Who does Daniel intend to speak with?",
    ["Marcus.", "The director.", "The client.", "The whole team."], 1),
  q("p2q5", `${HEADER_BASE} Part 2: Listening to a Daily Life Conversation`,
    "What does Priya's remark about the formatting imply?",
    ["The deck looks unprofessional.", "It is obvious to everyone that the deck is Daniel's work.", "Marcus reformatted the whole thing.", "The director prefers Marcus's style."], 1),

  /* ---------------- PART 3 — Listening for Information ---------------- */
  {
    id: "p3-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 3: Listening for Information`,
    sectionTitle: "Listening for Information",
    bullets: [
      "You will hear an informational segment. You will hear it only once.",
      "There are numbers, conditions, and exceptions. Track them carefully.",
    ],
  },
  {
    id: "p3-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 3: Listening for Information`,
    instruction: "Listen to a briefing from a city recycling coordinator. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.publicTalk,
    script: [
      { speaker: "Coordinator", text: "Thanks for coming. I want to walk you through the new three-stream collection system, because the rules changed on the first of the month and there's been a fair bit of confusion. So, three carts: blue for recycling, green for organics, and black for everything else — general waste. The single biggest change is that soft plastics — plastic bags, cling film, chip packets — no longer go in the blue cart. They used to; they don't now. They contaminate the recycling stream and jam the sorting machines, so as of this month they go in the black cart, or, better, you drop them at the return bins outside major grocery stores." },
      { speaker: "Coordinator", text: "Now, collection days. Black waste is collected every week. But here's the part people get wrong: blue and green are collected on alternating weeks, not every week. So in week one it's black and blue; in week two it's black and green; then it repeats. If you put your green cart out in a blue week, it simply won't be emptied, and it'll sit there for two weeks — which, with organics, you really don't want in summer." },
      { speaker: "Coordinator", text: "A couple of exceptions worth noting. Glass is recyclable, but not in the blue cart — it has its own drop-off depots, because broken glass injures sorting staff. And pizza boxes: the clean top half goes in blue, but the greasy bottom half goes in green, with the organics, not in recycling. Food-soiled cardboard is compostable, not recyclable. Finally, if your cart is more than a third full of the wrong material, our crews will leave a red tag and skip it, and you'll have to wait for the next cycle. So when in doubt, it's better to put something in general waste than to contaminate a whole cart." },
    ],
    transcript:
      "A recycling coordinator explains a new three-cart system: blue for recycling, green for organics, black for general waste. The key change is that soft plastics no longer go in blue — they go in black or to grocery-store return bins. Black is collected weekly; blue and green alternate weekly (week one black+blue, week two black+green). Exceptions: glass goes to its own depots (not blue), and pizza boxes split — clean top in blue, greasy bottom in green because food-soiled cardboard is compostable. Carts more than a third contaminated get a red tag and are skipped, so when unsure, use general waste.",
  },
  q("p3q1", `${HEADER_BASE} Part 3: Listening for Information`,
    "What is the single biggest change under the new system?",
    ["Glass now goes in the blue cart.", "Soft plastics no longer go in the blue recycling cart.", "There are now only two carts.", "Organics are collected weekly."], 1),
  q("p3q2", `${HEADER_BASE} Part 3: Listening for Information`,
    "How are the blue and green carts collected?",
    ["Both every week.", "On alternating weeks, not every week.", "Only once a month.", "On the same day as glass depots."], 1),
  q("p3q3", `${HEADER_BASE} Part 3: Listening for Information`,
    "In week two, which carts are collected?",
    ["Black and blue.", "Black and green.", "Blue and green.", "All three."], 1),
  q("p3q4", `${HEADER_BASE} Part 3: Listening for Information`,
    "Where does the greasy bottom half of a pizza box go?",
    ["The blue recycling cart.", "The green organics cart.", "A glass depot.", "The return bins at grocery stores."], 1),
  q("p3q5", `${HEADER_BASE} Part 3: Listening for Information`,
    "Why must glass be taken to its own depots?",
    ["It is not recyclable at all.", "Broken glass can injure sorting staff.", "It is collected weekly.", "It contaminates organics."], 1),
  q("p3q6", `${HEADER_BASE} Part 3: Listening for Information`,
    "What is the coordinator's overall advice when you are unsure?",
    ["Put the item in recycling to be safe.", "Put the item in general waste rather than risk contaminating a cart.", "Leave the item beside the cart.", "Call the depot for every item."], 1),

  /* ---------------- PART 4 — News Item ---------------- */
  {
    id: "p4-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 4: Listening to a News Item`,
    sectionTitle: "Listening to a News Item",
    bullets: [
      "You will hear a news report. You will hear it only once.",
      "Distinguish established facts from claims attributed to particular people.",
    ],
  },
  {
    id: "p4-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 4: Listening to a News Item`,
    instruction: "Listen to the news report. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.newsReport,
    script: [
      { speaker: "Anchor", text: "A pilot program that turned a stretch of the old riverside rail line into a linear park is being called a modest success — with some important caveats. The two-kilometre greenway opened last spring, and the city says foot traffic in the adjacent commercial district is up roughly eighteen percent compared with the same period a year earlier. Local business owners largely credit the park, though the city's own economists caution that a new transit stop opened nearby at the same time, making it hard to isolate the park's true effect." },
      { speaker: "Reporter", text: "That's right. So the headline number looks encouraging, but it comes with an asterisk. What's less disputed is the environmental piece: the corridor's restored native plantings have measurably improved stormwater drainage, and residents report noticeably cooler temperatures along the path in the evenings. The main complaint — and it's a persistent one — is parking. Several merchants say that while more people are walking through, delivery access has become more difficult since two service lanes were narrowed to make room for the path. The city has promised a review of loading zones by the autumn, but has stopped short of committing to reverse any of the changes." },
    ],
    transcript:
      "A riverside rail line converted into a two-kilometre linear park is deemed a modest success. Foot traffic in the adjacent commercial district is up about eighteen percent, which business owners credit to the park — but city economists warn a new nearby transit stop opened simultaneously, making the park's true effect hard to isolate. Less disputed benefits include improved stormwater drainage from native plantings and cooler evening temperatures. The main ongoing complaint is that delivery access worsened after two service lanes were narrowed. The city has promised a loading-zone review by autumn but has not committed to reversing the changes.",
  },
  q("p4q1", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "What was the riverside rail line converted into?",
    ["A transit station.", "A two-kilometre linear park.", "A parking structure.", "A shopping district."], 1),
  q("p4q2", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "Why do the city's economists urge caution about the rise in foot traffic?",
    ["The figure was based on a small survey.", "A new transit stop opened nearby at the same time, making the park's effect hard to isolate.", "Business owners refused to share their sales data.", "The increase happened only on weekends."], 1),
  q("p4q3", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "Which benefit is described as less disputed?",
    ["The rise in retail sales.", "Improved stormwater drainage and cooler evening temperatures.", "Increased parking availability.", "Faster delivery access."], 1),
  q("p4q4", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "What is the merchants' main complaint?",
    ["The park is too crowded.", "Delivery access worsened after service lanes were narrowed.", "The plantings block their storefronts.", "The transit stop is too far away."], 1),
  q("p4q5", `${HEADER_BASE} Part 4: Listening to a News Item`,
    "What has the city committed to so far?",
    ["Reversing the lane changes.", "A review of loading zones by autumn, without promising to undo anything.", "Building a second park.", "Closing the new transit stop."], 1),

  /* ---------------- PART 5 — Academic Discussion ---------------- */
  {
    id: "p5-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 5: Listening to a Discussion`,
    sectionTitle: "Listening to a Discussion",
    bullets: [
      "You will hear an extended discussion among three people. You will hear it only once.",
      "Track who holds which position and how their views differ.",
    ],
  },
  {
    id: "p5-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 5: Listening to a Discussion`,
    instruction: "Listen to three university students planning a group research project. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.campusDiscussion,
    script: [
      { speaker: "Tara", text: "Okay, so our topic is the impact of remote work on small towns. We've got three weeks. I think we should survey remote workers who've relocated — get primary data, first-hand accounts. That's what'll make the project stand out." },
      { speaker: "Owen", text: "I like the ambition, but three weeks is tight. Designing a good survey, distributing it, waiting for responses, then cleaning the data — that alone could eat the whole timeline. I'd rather build on existing datasets. There's census migration data and a couple of published studies we could synthesise. Less flashy, but far more reliable in the time we have." },
      { speaker: "Tara", text: "But secondary data is exactly what everyone else will use. It'll feel derivative." },
      { speaker: "Priya", text: "Can I offer a middle path? What if we anchor the project in the existing datasets — that guarantees we have something solid to submit — but we also run a small number of interviews, say five or six, purely to illustrate the trends with real voices? We're not claiming the interviews are statistically representative; they're colour, not proof." },
      { speaker: "Owen", text: "That I can get behind. Five interviews is manageable. My worry was never the interviews themselves — it was betting the whole grade on a survey that might not get enough responses in time." },
      { speaker: "Tara", text: "Hmm. I still think a survey would be richer, but I take the point about the timeline. And honestly, interviews might tell a better story than a thin survey with forty responses would. Fine — datasets as the backbone, interviews for illustration." },
      { speaker: "Priya", text: "Great. So Owen, could you take the lead on pulling and cleaning the census data, since that's your strength? Tara, you're clearly the people person — you handle recruiting and running the interviews. I'll build the framework that ties the two together and write the methodology section." },
      { speaker: "Owen", text: "Works for me. Let's set a hard deadline of end of week two for all data collection, so week three is purely analysis and writing. No collecting anything in the final week." },
      { speaker: "Tara", text: "Agreed. If I can't get five interviews by then, we go with whatever I have and don't chase more." },
    ],
    transcript:
      "Three students plan a three-week project on remote work's impact on small towns. Tara initially pushes for an original survey of relocated remote workers to make the project stand out. Owen objects that a survey is too risky in three weeks and prefers synthesising existing census and published data. Priya proposes a compromise: use existing datasets as the reliable backbone but add five or six illustrative interviews (colour, not statistical proof). Owen agrees since his concern was betting the grade on an uncertain survey, and Tara accepts, conceding interviews may tell a better story than a thin survey. They divide roles — Owen cleans census data, Tara runs interviews, Priya builds the framework and writes methodology — and set a hard end-of-week-two deadline for all data collection.",
  },
  q("p5q1", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What did Tara originally want to do?",
    ["Rely entirely on published studies.", "Run an original survey of relocated remote workers.", "Interview local business owners only.", "Change the project topic."], 1),
  q("p5q2", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What was Owen's main objection to the survey?",
    ["Surveys are unethical.", "The three-week timeline made getting enough responses too risky.", "He dislikes working with people.", "Surveys cost too much money."], 1),
  q("p5q3", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What compromise does Priya propose?",
    ["Drop the interviews entirely.", "Use existing datasets as the backbone plus a few interviews for illustration.", "Extend the deadline by two weeks.", "Split into two separate projects."], 1),
  q("p5q4", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "How does the group regard the interviews' role?",
    ["As the main statistical evidence.", "As illustration and colour, not statistical proof.", "As a backup if the datasets fail.", "As optional if there is time."], 1),
  q("p5q5", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "Why is Owen assigned the census data?",
    ["He asked for the easiest task.", "It plays to his strength.", "No one else was available.", "He proposed the topic."], 1),
  q("p5q6", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What does Tara ultimately concede?",
    ["That the topic should change.", "That interviews may tell a better story than a thin survey would.", "That Owen should lead the whole project.", "That three weeks is plenty of time for a survey."], 1),
  q("p5q7", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What is the purpose of the end-of-week-two deadline?",
    ["To submit the project early.", "To leave week three purely for analysis and writing.", "To give Tara more time for interviews.", "To match the library's schedule."], 1),
  q("p5q8", `${HEADER_BASE} Part 5: Listening to a Discussion`,
    "What will Tara do if she cannot get five interviews in time?",
    ["Extend the deadline.", "Proceed with whatever she has and not chase more.", "Switch to a survey.", "Ask Owen to do interviews instead."], 1),

  /* ---------------- PART 6 — Viewpoints ---------------- */
  {
    id: "p6-instr",
    kind: "instruction",
    headerTitle: `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    sectionTitle: "Listening to Viewpoints",
    bullets: [
      "You will hear a recorded segment presenting a debate. You will hear it only once.",
      "Separate the interviewer's framing from each expert's actual position.",
    ],
  },
  {
    id: "p6-audio",
    kind: "audio",
    headerTitle: `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    instruction: "Listen to a radio segment about whether cities should ban private cars from downtown cores. You will hear it only once.",
    blueprint: LISTENING_BLUEPRINT.interview,
    script: [
      { speaker: "Host", text: "The idea of car-free downtowns is spreading. With us are urban planner Dr. Chen and small-business advocate Ms. Alvarez. Dr. Chen, you support restrictions — but I understand you don't back an outright ban?" },
      { speaker: "Dr. Chen", text: "Correct, and that distinction matters. A blanket ban is politically toxic and, frankly, unnecessary. What actually works is a congestion charge paired with excellent transit — you price scarce road space, you reinvest that revenue in buses and bike lanes, and people voluntarily shift. Cities that tried hard bans without first building alternatives simply exported their traffic to the ring roads and angered everyone. Sequence is everything: alternatives first, then restrictions." },
      { speaker: "Host", text: "Ms. Alvarez, you represent downtown retailers. I imagine you're firmly opposed?" },
      { speaker: "Ms. Alvarez", text: "People assume that, but it's more nuanced. My members aren't against pedestrianisation in principle — several have seen sales rise on car-free streets, because people linger and browse when they're not dodging traffic. Our real fear is a poorly managed transition: if you remove parking and car access before transit is genuinely convenient, you strand the suburban customers who drive in to spend money. So oddly, Dr. Chen and I agree on the sequence. Where I push back is on the congestion charge specifically — I worry it's regressive, that it hits my delivery drivers and lower-income staff hardest." },
      { speaker: "Dr. Chen", text: "And that's a fair critique. I'd address it with exemptions and rebates for commercial vehicles and low-income residents. The tool isn't perfect, but a well-designed charge with carve-outs beats both doing nothing and a clumsy ban." },
      { speaker: "Host", text: "So, interestingly, less disagreement than our listeners might expect." },
      { speaker: "Ms. Alvarez", text: "On the goal, yes. On the mechanism, we still differ — but we're arguing about how, not whether." },
    ],
    transcript:
      "A radio debate on car-free downtowns. Dr. Chen, an urban planner, supports restrictions but opposes an outright ban; he favours a congestion charge funding transit, insisting alternatives must come before restrictions. Ms. Alvarez, a small-business advocate, is not opposed to pedestrianisation in principle — some retailers see higher sales on car-free streets — but fears a poorly sequenced transition that strands driving suburban customers, and she specifically objects that a congestion charge is regressive on delivery drivers and low-income staff. Dr. Chen concedes this and proposes exemptions and rebates. Both agree on sequence and goals; they differ mainly on the mechanism.",
  },
  q("p6q1", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "What is Dr. Chen's position?",
    ["An immediate outright ban on all downtown cars.", "Restrictions via a congestion charge, but only after building transit alternatives.", "No restrictions of any kind.", "Banning only commercial vehicles."], 1),
  q("p6q2", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "Why does Dr. Chen say hard bans have failed elsewhere?",
    ["They were too expensive to enforce.", "They exported traffic to ring roads because alternatives weren't built first.", "Drivers ignored them completely.", "They reduced downtown sales."], 1),
  q("p6q3", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "What is Ms. Alvarez's actual view of pedestrianisation?",
    ["She opposes it entirely.", "She is not against it in principle; some retailers see higher sales.", "She wants it introduced overnight.", "She thinks it only helps large chains."], 1),
  q("p6q4", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "What is Ms. Alvarez's specific objection to a congestion charge?",
    ["It is too small to change behaviour.", "It is regressive, hitting delivery drivers and lower-income staff hardest.", "It would require new technology.", "It benefits suburban drivers unfairly."], 1),
  q("p6q5", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "How does Dr. Chen respond to that objection?",
    ["He dismisses it as irrelevant.", "He proposes exemptions and rebates for commercial vehicles and low-income residents.", "He suggests raising the charge instead.", "He agrees the charge should be scrapped."], 1),
  q("p6q6", `${HEADER_BASE} Part 6: Listening to Viewpoints`,
    "What does the exchange reveal about the two guests?",
    ["They disagree about almost everything.", "They agree on the goal and sequence but differ on the mechanism.", "They both oppose any downtown changes.", "They fully agree, including on the congestion charge."], 1),

  {
    id: "result",
    kind: "result",
    headerTitle: `${HEADER_BASE} Results`,
  },
]

export const listeningTest4: MockTest = {
  id: "listening-4",
  title: "CELPIP Listening — Advanced Practice Test 4",
  section: "listening",
  description:
    "A high-difficulty CELPIP-style Listening test with six parts and longer, denser audio: problem solving, a daily-life conversation, an information briefing, a news report, an extended academic discussion, and contrasting viewpoints. Inference and detail-trap heavy.",
  durationLabel: "45–50 min",
  questionCount: 38,
  steps,
}
